version: '3.4'

name: hcsys
services:
  api:
    image: ${API_IMAGE_PATH}:${API_TAG}
    build:
      context: .
      dockerfile: HCSYS.Api/Dockerfile
    environment:
      - ConnectionStrings__Default=${DEFAULT_CONNECTION_STRING} 
    ports:
      - ${API_EXTERNAL_PORT:-8000}:8080

networks:
  default:
    name: hcsys
