version: '3.4'

name: hcsys
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    ports:
      - ${DB_EXTERNAL_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    ports:
      - ${PGADMIN_EXTERNAL_PORT:-5050}:80
    volumes:
      - pgadmin_data:/root/.pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: hcsys