version: '3.4'

services:
  db:
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    ports:
      - ${PGADMIN_EXTERNAL_PORT:-5050}:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ENVIRONMENT}
    ports:
      - ${API_EXTERNAL_PORT:-8000}:8080
